name: proy_test
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  intl: ^0.17.0
  image_picker: ^1.1.2
  bitsdojo_window: ^0.1.6
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - images/

flutter_icons:
  android: true
  ios: true
  image_path: "images/PICNITO LOGO.jpeg" # Ruta de tu icono
  #adaptive_icon_background: "#ffffff"    # Opcional, para Android 8+
  #adaptive_icon_foreground: "assets/icon/app_icon_foreground.png" # Opcional

